services:
  - type: web
    name: backend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./backend/Dockerfile
    buildCommand: ""  # not needed for docker env
    startCommand: ""  # use CMD in Dockerfile
    healthCheckPath: /docs
    envVars:
      - key: DATABASE_URL
        value: <YOUR_RENDER_POSTGRES_URL>

  - type: web
    name: frontend
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: ""
    startCommand: ""
